import type { EditorThemeClasses } from 'lexical';

const theme: EditorThemeClasses = {
  root: 'twd h-full w-full p-4 focus:outline-none',
  link: 'twd cursor-pointer text-blue-500 hover:text-blue-600 hover:underline',
  text: {
    bold: 'twd font-semibold',
    underline: 'twd underline',
    italic: 'twd italic',
    strikethrough: 'twd line-through',
    underlineStrikethrough: 'twd underline-line-through',
    code: 'twd font-mono bg-neutral-100 dark:bg-neutral-800 px-1 py-0.5 rounded text-sm',
  },
  paragraph: 'twd my-2',
  heading: {
    h1: 'twd text-3xl font-bold mt-6 mb-4',
    h2: 'twd text-2xl font-bold mt-5 mb-3',
    h3: 'twd text-xl font-bold mt-4 mb-2',
    h4: 'twd text-lg font-bold mt-3 mb-1',
    h5: 'twd text-base font-bold mt-2 mb-1',
    h6: 'twd text-sm font-bold mt-2 mb-1',
  },
  list: {
    ul: 'twd list-disc pl-8 my-3',
    ol: 'twd list-decimal pl-8 my-3',
    listitem: 'twd my-1',
    nested: {
      listitem: 'twd my-1',
    },
    checklist: 'twd flex items-center gap-2',
  },
  quote:
    'twd border-l-4 border-neutral-300 dark:border-neutral-700 pl-4 py-1 my-4 focus:border-none italic text-neutral-700 dark:text-neutral-300',
  code: 'twd font-mono bg-neutral-100 dark:bg-neutral-800 rounded py-3 px-2 my-4 overflow-x-auto text-sm',
  codeHighlight: {
    atrule: 'twd text-blue-600 dark:text-blue-400',
    attr: 'twd text-purple-600 dark:text-purple-400',
    boolean: 'twd text-red-600 dark:text-red-400',
    builtin: 'twd text-green-600 dark:text-green-400',
    cdata: 'twd text-gray-600 dark:text-gray-400',
    char: 'twd text-green-600 dark:text-green-400',
    class: 'twd text-yellow-600 dark:text-yellow-400',
    'class-name': 'twd text-yellow-600 dark:text-yellow-400',
    comment: 'twd text-gray-500 italic',
    constant: 'twd text-purple-600 dark:text-purple-400',
    deleted: 'twd text-red-600 dark:text-red-400 line-through',
    doctype: 'twd text-gray-600 dark:text-gray-400',
    entity: 'twd text-green-600 dark:text-green-400',
    function: 'twd text-blue-600 dark:text-blue-400',
    important: 'twd text-red-600 dark:text-red-400 font-bold',
    inserted: 'twd text-green-600 dark:text-green-400',
    keyword: 'twd text-purple-600 dark:text-purple-400',
    namespace: 'twd text-yellow-600 dark:text-yellow-400',
    number: 'twd text-orange-600 dark:text-orange-400',
    operator: 'twd text-purple-600 dark:text-purple-400',
    prolog: 'twd text-gray-600 dark:text-gray-400',
    property: 'twd text-blue-600 dark:text-blue-400',
    punctuation: 'twd text-gray-600 dark:text-gray-400',
    regex: 'twd text-orange-600 dark:text-orange-400',
    selector: 'twd text-green-600 dark:text-green-400',
    string: 'twd text-green-600 dark:text-green-400',
    symbol: 'twd text-purple-600 dark:text-purple-400',
    tag: 'twd text-red-600 dark:text-red-400',
    url: 'twd text-blue-600 dark:text-blue-400 underline',
    variable: 'twd text-orange-600 dark:text-orange-400',
  },
  table: 'twd border-collapse w-full my-4',
  tableCell: 'twd border border-neutral-300 dark:border-neutral-700 px-3 py-2',
  tableRow: 'twd border-b border-neutral-300 dark:border-neutral-700',
  tableHeader:
    'twd bg-neutral-100 dark:bg-neutral-800 font-bold text-left px-3 py-2 border border-neutral-300 dark:border-neutral-700',
  image: 'twd max-w-full h-auto my-4',
  mark: 'twd bg-yellow-200 dark:bg-yellow-800 px-1 rounded',
  hr: 'twd my-6 border-t border-neutral-300 dark:border-neutral-700',
};

export default theme;
